export const routesList = {
  app: "/",
  addProducts: "/add-products",
  allProducts: "/all-products",
  statistics: "/statistics",
  users: "users",
  invoices: "invoices",
  settings: "settings",
  login: "login",
  signUp: "sign-up",
  resetPassword: "reset-password",
  category: "category",
  addCategory: "add-Category",
  orders: "orders",
};
